import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'surface':                    '#001524',
        'surface-dim':                '#001524',
        'surface-bright':             '#273b4c',
        'surface-container-lowest':   '#00101c',
        'surface-container-low':      '#071d2d',
        'surface-container':          '#0b2131',
        'surface-container-high':     '#172c3c',
        'surface-container-highest':  '#223747',
        'surface-variant':            '#223747',
        'surface-tint':               '#a5cce6',
        'on-surface':                 '#cfe5fa',
        'on-surface-variant':         '#c1c7cd',
        'background':                 '#001524',
        'on-background':              '#cfe5fa',
        'primary':                    '#a5cce6',
        'primary-fixed':              '#c5e7ff',
        'primary-fixed-dim':          '#a5cce6',
        'primary-container':          '#7fa5be',
        'on-primary':                 '#053449',
        'on-primary-fixed':           '#001e2d',
        'on-primary-fixed-variant':   '#234b61',
        'on-primary-container':       '#103b50',
        'inverse-primary':            '#3d6379',
        'secondary':                  '#bbc9cf',
        'secondary-fixed':            '#d7e5eb',
        'secondary-fixed-dim':        '#bbc9cf',
        'secondary-container':        '#3e4b50',
        'on-secondary':               '#253237',
        'on-secondary-fixed':         '#101d22',
        'on-secondary-fixed-variant': '#3c494e',
        'on-secondary-container':     '#adbbc1',
        'tertiary':                   '#f0bd8d',
        'tertiary-fixed':             '#ffdcbe',
        'tertiary-fixed-dim':         '#f0bd8d',
        'tertiary-container':         '#c6976a',
        'on-tertiary':                '#482905',
        'on-tertiary-fixed':          '#2d1600',
        'on-tertiary-fixed-variant':  '#623f1a',
        'on-tertiary-container':      '#50300b',
        'outline':                    '#8c9197',
        'outline-variant':            '#42484c',
        'inverse-surface':            '#cfe5fa',
        'inverse-on-surface':         '#1e3243',
        'error':                      '#ffb4ab',
        'error-container':            '#93000a',
        'on-error':                   '#690005',
        'on-error-container':         '#ffdad6',
      },
      fontFamily: {
        headline: ['var(--font-noto-serif)', 'Noto Serif', 'Georgia', 'serif'],
        body:     ['var(--font-manrope)', 'Manrope', 'system-ui', 'sans-serif'],
        label:    ['var(--font-manrope)', 'Manrope', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.125rem',
        md:      '0.25rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        full:    '0.75rem',
      },
    },
  },
  plugins: [],
}

export default config
