-- Ids are generated by the app and are usually UUIDs, but not guaranteed
-- (e.g. the legacy landing "dummy-landing-1234"), so store them as text.
-- Only needed on databases created with the original 0001_init.sql;
-- 0001 has been updated to use text ids for fresh installs.

alter table public.blog_posts alter column id type text;
alter table public.landings   alter column id type text;
